title: Just the Docs
description: My documentation using Jeykll site with Just the Docs theme!
theme: just-the-docs

url: https://bakhtik.github.io/docs

aux_links:
  Docs Repository: https://github.com/bakhtik/docs
